{
 "title": "Autoscaling Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    { "expr": "nomad_client_host_memory_used" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(nomad_client_host_cpu_total)"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg((haproxy_server_current_sessions{backend=\"http_back\"}) and (haproxy_server_up{backend=\"http_back\"} == 1))",
     "legendFormat": "avg"
    },
    {
     "expr": "(haproxy_server_current_sessions{backend=\"http_back\"}) and (haproxy_server_up{backend=\"http_back\"} == 1)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Webapp group count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nomad_nomad_job_summary_running{task_group=\"demo\"}",
     "legendFormat": "{{task_group}}"
    }
   ]
  },
  {
   "title": "Avg. connections/instance",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg((haproxy_server_current_sessions{backend=\"http_back\"}) and (haproxy_server_up{backend=\"http_back\"} == 1))"
    }
   ]
  }
 ]
}