// Copyright IBM Corp. 2020, 2025
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugins/apm/proto/v1/apm.proto

package proto

import (
	v1 "github.com/hashicorp/nomad-autoscaler/plugins/shared/proto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TimeRange     *v1.TimeRange          `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_plugins_apm_proto_v1_apm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_apm_proto_v1_apm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_plugins_apm_proto_v1_apm_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetTimeRange() *v1.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

type QueryResponse struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	TimestampedMetric []*v1.TimestampedMetric `protobuf:"bytes,1,rep,name=timestamped_metric,json=timestampedMetric,proto3" json:"timestamped_metric,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_plugins_apm_proto_v1_apm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_apm_proto_v1_apm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_plugins_apm_proto_v1_apm_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetTimestampedMetric() []*v1.TimestampedMetric {
	if x != nil {
		return x.TimestampedMetric
	}
	return nil
}

type QueryMultipleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TimeRange     *v1.TimeRange          `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMultipleRequest) Reset() {
	*x = QueryMultipleRequest{}
	mi := &file_plugins_apm_proto_v1_apm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMultipleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMultipleRequest) ProtoMessage() {}

func (x *QueryMultipleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_apm_proto_v1_apm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMultipleRequest.ProtoReflect.Descriptor instead.
func (*QueryMultipleRequest) Descriptor() ([]byte, []int) {
	return file_plugins_apm_proto_v1_apm_proto_rawDescGZIP(), []int{2}
}

func (x *QueryMultipleRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryMultipleRequest) GetTimeRange() *v1.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

type QueryMultipleResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TimestampedMetric []*QueryResponse       `protobuf:"bytes,1,rep,name=timestamped_metric,json=timestampedMetric,proto3" json:"timestamped_metric,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueryMultipleResponse) Reset() {
	*x = QueryMultipleResponse{}
	mi := &file_plugins_apm_proto_v1_apm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMultipleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMultipleResponse) ProtoMessage() {}

func (x *QueryMultipleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_apm_proto_v1_apm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMultipleResponse.ProtoReflect.Descriptor instead.
func (*QueryMultipleResponse) Descriptor() ([]byte, []int) {
	return file_plugins_apm_proto_v1_apm_proto_rawDescGZIP(), []int{3}
}

func (x *QueryMultipleResponse) GetTimestampedMetric() []*QueryResponse {
	if x != nil {
		return x.TimestampedMetric
	}
	return nil
}

var File_plugins_apm_proto_v1_apm_proto protoreflect.FileDescriptor

const file_plugins_apm_proto_v1_apm_proto_rawDesc = "" +
	"\n" +
	"\x1eplugins/apm/proto/v1/apm.proto\x12/hashicorp.nomad_autoscaler.plugins.apm.proto.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$plugins/shared/proto/v1/shared.proto\"\x82\x01\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\\\n" +
	"\n" +
	"time_range\x18\x02 \x01(\v2=.hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimeRangeR\ttimeRange\"\x85\x01\n" +
	"\rQueryResponse\x12t\n" +
	"\x12timestamped_metric\x18\x01 \x03(\v2E.hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimestampedMetricR\x11timestampedMetric\"\x8a\x01\n" +
	"\x14QueryMultipleRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\\\n" +
	"\n" +
	"time_range\x18\x02 \x01(\v2=.hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimeRangeR\ttimeRange\"\x86\x01\n" +
	"\x15QueryMultipleResponse\x12m\n" +
	"\x12timestamped_metric\x18\x01 \x03(\v2>.hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryResponseR\x11timestampedMetric2\xc0\x02\n" +
	"\x10APMPluginService\x12\x88\x01\n" +
	"\x05Query\x12=.hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryRequest\x1a>.hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryResponse\"\x00\x12\xa0\x01\n" +
	"\rQueryMultiple\x12E.hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryMultipleRequest\x1aF.hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryMultipleResponse\"\x00B\aZ\x05protob\x06proto3"

var (
	file_plugins_apm_proto_v1_apm_proto_rawDescOnce sync.Once
	file_plugins_apm_proto_v1_apm_proto_rawDescData []byte
)

func file_plugins_apm_proto_v1_apm_proto_rawDescGZIP() []byte {
	file_plugins_apm_proto_v1_apm_proto_rawDescOnce.Do(func() {
		file_plugins_apm_proto_v1_apm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugins_apm_proto_v1_apm_proto_rawDesc), len(file_plugins_apm_proto_v1_apm_proto_rawDesc)))
	})
	return file_plugins_apm_proto_v1_apm_proto_rawDescData
}

var file_plugins_apm_proto_v1_apm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_plugins_apm_proto_v1_apm_proto_goTypes = []any{
	(*QueryRequest)(nil),          // 0: hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryRequest
	(*QueryResponse)(nil),         // 1: hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryResponse
	(*QueryMultipleRequest)(nil),  // 2: hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryMultipleRequest
	(*QueryMultipleResponse)(nil), // 3: hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryMultipleResponse
	(*v1.TimeRange)(nil),          // 4: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimeRange
	(*v1.TimestampedMetric)(nil),  // 5: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimestampedMetric
}
var file_plugins_apm_proto_v1_apm_proto_depIdxs = []int32{
	4, // 0: hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryRequest.time_range:type_name -> hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimeRange
	5, // 1: hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryResponse.timestamped_metric:type_name -> hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimestampedMetric
	4, // 2: hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryMultipleRequest.time_range:type_name -> hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimeRange
	1, // 3: hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryMultipleResponse.timestamped_metric:type_name -> hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryResponse
	0, // 4: hashicorp.nomad_autoscaler.plugins.apm.proto.v1.APMPluginService.Query:input_type -> hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryRequest
	2, // 5: hashicorp.nomad_autoscaler.plugins.apm.proto.v1.APMPluginService.QueryMultiple:input_type -> hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryMultipleRequest
	1, // 6: hashicorp.nomad_autoscaler.plugins.apm.proto.v1.APMPluginService.Query:output_type -> hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryResponse
	3, // 7: hashicorp.nomad_autoscaler.plugins.apm.proto.v1.APMPluginService.QueryMultiple:output_type -> hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryMultipleResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_plugins_apm_proto_v1_apm_proto_init() }
func file_plugins_apm_proto_v1_apm_proto_init() {
	if File_plugins_apm_proto_v1_apm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugins_apm_proto_v1_apm_proto_rawDesc), len(file_plugins_apm_proto_v1_apm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugins_apm_proto_v1_apm_proto_goTypes,
		DependencyIndexes: file_plugins_apm_proto_v1_apm_proto_depIdxs,
		MessageInfos:      file_plugins_apm_proto_v1_apm_proto_msgTypes,
	}.Build()
	File_plugins_apm_proto_v1_apm_proto = out.File
	file_plugins_apm_proto_v1_apm_proto_goTypes = nil
	file_plugins_apm_proto_v1_apm_proto_depIdxs = nil
}
