// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugins/apm/proto/v1/apm.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	v1 "github.com/hashicorp/nomad-autoscaler/plugins/shared/proto/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryRequest struct {
	Query                string        `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TimeRange            *v1.TimeRange `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1464f598a5295874, []int{0}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *QueryRequest) GetTimeRange() *v1.TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

type QueryResponse struct {
	TimestampedMetric    []*v1.TimestampedMetric `protobuf:"bytes,1,rep,name=timestamped_metric,json=timestampedMetric,proto3" json:"timestamped_metric,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1464f598a5295874, []int{1}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetTimestampedMetric() []*v1.TimestampedMetric {
	if m != nil {
		return m.TimestampedMetric
	}
	return nil
}

type QueryMultipleRequest struct {
	Query                string        `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TimeRange            *v1.TimeRange `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QueryMultipleRequest) Reset()         { *m = QueryMultipleRequest{} }
func (m *QueryMultipleRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMultipleRequest) ProtoMessage()    {}
func (*QueryMultipleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1464f598a5295874, []int{2}
}

func (m *QueryMultipleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMultipleRequest.Unmarshal(m, b)
}
func (m *QueryMultipleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMultipleRequest.Marshal(b, m, deterministic)
}
func (m *QueryMultipleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMultipleRequest.Merge(m, src)
}
func (m *QueryMultipleRequest) XXX_Size() int {
	return xxx_messageInfo_QueryMultipleRequest.Size(m)
}
func (m *QueryMultipleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMultipleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMultipleRequest proto.InternalMessageInfo

func (m *QueryMultipleRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *QueryMultipleRequest) GetTimeRange() *v1.TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

type QueryMultipleResponse struct {
	TimestampedMetric    []*QueryResponse `protobuf:"bytes,1,rep,name=timestamped_metric,json=timestampedMetric,proto3" json:"timestamped_metric,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QueryMultipleResponse) Reset()         { *m = QueryMultipleResponse{} }
func (m *QueryMultipleResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMultipleResponse) ProtoMessage()    {}
func (*QueryMultipleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1464f598a5295874, []int{3}
}

func (m *QueryMultipleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMultipleResponse.Unmarshal(m, b)
}
func (m *QueryMultipleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMultipleResponse.Marshal(b, m, deterministic)
}
func (m *QueryMultipleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMultipleResponse.Merge(m, src)
}
func (m *QueryMultipleResponse) XXX_Size() int {
	return xxx_messageInfo_QueryMultipleResponse.Size(m)
}
func (m *QueryMultipleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMultipleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMultipleResponse proto.InternalMessageInfo

func (m *QueryMultipleResponse) GetTimestampedMetric() []*QueryResponse {
	if m != nil {
		return m.TimestampedMetric
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryRequest)(nil), "hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryResponse")
	proto.RegisterType((*QueryMultipleRequest)(nil), "hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryMultipleRequest")
	proto.RegisterType((*QueryMultipleResponse)(nil), "hashicorp.nomad_autoscaler.plugins.apm.proto.v1.QueryMultipleResponse")
}

func init() {
	proto.RegisterFile("plugins/apm/proto/v1/apm.proto", fileDescriptor_1464f598a5295874)
}

var fileDescriptor_1464f598a5295874 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x53, 0xc1, 0x4b, 0xfb, 0x30,
	0x18, 0xfd, 0x65, 0x3f, 0xa6, 0x2c, 0x53, 0xd0, 0x30, 0x61, 0xf4, 0xa0, 0xa3, 0x78, 0xd8, 0x29,
	0x65, 0xf3, 0x3c, 0x41, 0x61, 0xde, 0x06, 0xb3, 0x7a, 0x12, 0x61, 0xc4, 0xee, 0xb3, 0x2b, 0x34,
	0x4d, 0x96, 0xa4, 0x05, 0xaf, 0x82, 0x22, 0xfe, 0x15, 0xfe, 0x29, 0xfe, 0x69, 0xd2, 0xb4, 0x9d,
	0x3a, 0x44, 0x74, 0x3b, 0x78, 0x4a, 0x5e, 0xf8, 0xbe, 0xf7, 0x5e, 0x5e, 0xbe, 0xe0, 0x7d, 0x19,
	0xa7, 0x61, 0x94, 0x68, 0x8f, 0x49, 0xee, 0x49, 0x25, 0x8c, 0xf0, 0xb2, 0x5e, 0x0e, 0xa8, 0x05,
	0xc4, 0x9b, 0x31, 0x3d, 0x8b, 0x02, 0xa1, 0x24, 0x4d, 0x04, 0x67, 0xd3, 0x09, 0x4b, 0x8d, 0xd0,
	0x01, 0x8b, 0x41, 0xd1, 0xb2, 0x95, 0x2e, 0xaa, 0x69, 0xd6, 0x73, 0x0e, 0x42, 0x21, 0xc2, 0x18,
	0x0a, 0xae, 0x9b, 0xf4, 0xd6, 0x33, 0x11, 0x07, 0x6d, 0x18, 0x97, 0x45, 0x8d, 0x73, 0x58, 0x29,
	0xea, 0x19, 0x53, 0x30, 0x7d, 0x17, 0x2d, 0x70, 0x51, 0xe5, 0xde, 0x23, 0xbc, 0x75, 0x9e, 0x82,
	0xba, 0xf3, 0x61, 0x9e, 0x82, 0x36, 0xa4, 0x85, 0xeb, 0xf3, 0x1c, 0xb7, 0x51, 0x07, 0x75, 0x1b,
	0x7e, 0x01, 0xc8, 0x35, 0xc6, 0x39, 0xff, 0x44, 0xb1, 0x24, 0x84, 0x76, 0xad, 0x83, 0xba, 0xcd,
	0xfe, 0x80, 0xfe, 0xc0, 0xf3, 0x47, 0x31, 0x9a, 0xf5, 0xe8, 0x65, 0xc4, 0xc1, 0xcf, 0x49, 0xfc,
	0x86, 0xa9, 0xb6, 0xee, 0x03, 0xc2, 0xdb, 0xa5, 0x09, 0x2d, 0x45, 0xa2, 0x81, 0x18, 0x4c, 0x16,
	0xf7, 0x81, 0xe9, 0x84, 0x83, 0x51, 0x51, 0xd0, 0x46, 0x9d, 0xff, 0xdd, 0x66, 0x7f, 0xb8, 0xaa,
	0x6e, 0xc9, 0x36, 0xb2, 0x64, 0xfe, 0xae, 0x59, 0x3e, 0x72, 0x9f, 0x11, 0x6e, 0x59, 0x1f, 0xa3,
	0x34, 0x36, 0x91, 0x8c, 0xe1, 0x2f, 0x43, 0x79, 0x44, 0x78, 0x6f, 0xc9, 0x4c, 0x19, 0x0e, 0xff,
	0x26, 0x9c, 0x63, 0xfa, 0xcb, 0x41, 0xa2, 0x9f, 0x82, 0xff, 0x22, 0x95, 0xfe, 0x6b, 0x0d, 0xef,
	0x9c, 0x8c, 0x47, 0x63, 0xdb, 0x7c, 0x01, 0x2a, 0x8b, 0x02, 0x20, 0x4f, 0x08, 0xd7, 0x6d, 0x27,
	0x19, 0xac, 0xaa, 0x68, 0xa3, 0x75, 0xd6, 0x34, 0xec, 0xfe, 0x23, 0x2f, 0xd5, 0xf4, 0x54, 0x41,
	0x91, 0xe1, 0x6a, 0x9c, 0x4b, 0xaf, 0xee, 0x9c, 0xad, 0x4b, 0x53, 0x59, 0x3c, 0xdd, 0xbc, 0xaa,
	0x17, 0xff, 0x74, 0xc3, 0x2e, 0x47, 0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xef, 0x4e, 0x7c, 0x96,
	0x0f, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// APMPluginServiceClient is the client API for APMPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APMPluginServiceClient interface {
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	QueryMultiple(ctx context.Context, in *QueryMultipleRequest, opts ...grpc.CallOption) (*QueryMultipleResponse, error)
}

type aPMPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAPMPluginServiceClient(cc grpc.ClientConnInterface) APMPluginServiceClient {
	return &aPMPluginServiceClient{cc}
}

func (c *aPMPluginServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad_autoscaler.plugins.apm.proto.v1.APMPluginService/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPMPluginServiceClient) QueryMultiple(ctx context.Context, in *QueryMultipleRequest, opts ...grpc.CallOption) (*QueryMultipleResponse, error) {
	out := new(QueryMultipleResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad_autoscaler.plugins.apm.proto.v1.APMPluginService/QueryMultiple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APMPluginServiceServer is the server API for APMPluginService service.
type APMPluginServiceServer interface {
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	QueryMultiple(context.Context, *QueryMultipleRequest) (*QueryMultipleResponse, error)
}

// UnimplementedAPMPluginServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAPMPluginServiceServer struct {
}

func (*UnimplementedAPMPluginServiceServer) Query(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedAPMPluginServiceServer) QueryMultiple(ctx context.Context, req *QueryMultipleRequest) (*QueryMultipleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMultiple not implemented")
}

func RegisterAPMPluginServiceServer(s *grpc.Server, srv APMPluginServiceServer) {
	s.RegisterService(&_APMPluginService_serviceDesc, srv)
}

func _APMPluginService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APMPluginServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad_autoscaler.plugins.apm.proto.v1.APMPluginService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APMPluginServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APMPluginService_QueryMultiple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMultipleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APMPluginServiceServer).QueryMultiple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad_autoscaler.plugins.apm.proto.v1.APMPluginService/QueryMultiple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APMPluginServiceServer).QueryMultiple(ctx, req.(*QueryMultipleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _APMPluginService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hashicorp.nomad_autoscaler.plugins.apm.proto.v1.APMPluginService",
	HandlerType: (*APMPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _APMPluginService_Query_Handler,
		},
		{
			MethodName: "QueryMultiple",
			Handler:    _APMPluginService_QueryMultiple_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugins/apm/proto/v1/apm.proto",
}
