// Copyright IBM Corp. 2020, 2025
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: plugins/apm/proto/v1/apm.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	APMPluginService_Query_FullMethodName         = "/hashicorp.nomad_autoscaler.plugins.apm.proto.v1.APMPluginService/Query"
	APMPluginService_QueryMultiple_FullMethodName = "/hashicorp.nomad_autoscaler.plugins.apm.proto.v1.APMPluginService/QueryMultiple"
)

// APMPluginServiceClient is the client API for APMPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APMPluginServiceClient interface {
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	QueryMultiple(ctx context.Context, in *QueryMultipleRequest, opts ...grpc.CallOption) (*QueryMultipleResponse, error)
}

type aPMPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAPMPluginServiceClient(cc grpc.ClientConnInterface) APMPluginServiceClient {
	return &aPMPluginServiceClient{cc}
}

func (c *aPMPluginServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, APMPluginService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPMPluginServiceClient) QueryMultiple(ctx context.Context, in *QueryMultipleRequest, opts ...grpc.CallOption) (*QueryMultipleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMultipleResponse)
	err := c.cc.Invoke(ctx, APMPluginService_QueryMultiple_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APMPluginServiceServer is the server API for APMPluginService service.
// All implementations should embed UnimplementedAPMPluginServiceServer
// for forward compatibility.
type APMPluginServiceServer interface {
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	QueryMultiple(context.Context, *QueryMultipleRequest) (*QueryMultipleResponse, error)
}

// UnimplementedAPMPluginServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPMPluginServiceServer struct{}

func (UnimplementedAPMPluginServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedAPMPluginServiceServer) QueryMultiple(context.Context, *QueryMultipleRequest) (*QueryMultipleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMultiple not implemented")
}
func (UnimplementedAPMPluginServiceServer) testEmbeddedByValue() {}

// UnsafeAPMPluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APMPluginServiceServer will
// result in compilation errors.
type UnsafeAPMPluginServiceServer interface {
	mustEmbedUnimplementedAPMPluginServiceServer()
}

func RegisterAPMPluginServiceServer(s grpc.ServiceRegistrar, srv APMPluginServiceServer) {
	// If the following call pancis, it indicates UnimplementedAPMPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&APMPluginService_ServiceDesc, srv)
}

func _APMPluginService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APMPluginServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APMPluginService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APMPluginServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APMPluginService_QueryMultiple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMultipleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APMPluginServiceServer).QueryMultiple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APMPluginService_QueryMultiple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APMPluginServiceServer).QueryMultiple(ctx, req.(*QueryMultipleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// APMPluginService_ServiceDesc is the grpc.ServiceDesc for APMPluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APMPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hashicorp.nomad_autoscaler.plugins.apm.proto.v1.APMPluginService",
	HandlerType: (*APMPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _APMPluginService_Query_Handler,
		},
		{
			MethodName: "QueryMultiple",
			Handler:    _APMPluginService_QueryMultiple_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugins/apm/proto/v1/apm.proto",
}
