# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # Expose ports to the host.
  config.vm.network "forwarded_port", guest: 4646, host: 4646, host_ip: "127.0.0.1"    # Nomad
  config.vm.network "forwarded_port", guest: 8500, host: 8500, host_ip: "127.0.0.1"    # Consul UI
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"    # Nomad Autoscaler health check
  config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"    # Demo webapp
  config.vm.network "forwarded_port", guest: 1936, host: 1936, host_ip: "127.0.0.1"    # HAProxy stats
  config.vm.network "forwarded_port", guest: 9090, host: 9090, host_ip: "127.0.0.1"    # Prometheus
  config.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1"    # Grafana

  # Share current directory with jobs and configuration files with the VM.
  config.vm.synced_folder "./", "/home/vagrant/nomad-autoscaler"

  # VM configuration.
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  # Provision demo dependencies.
  #   - Downloads and install Nomad, Consul and Docker
  # Only runs when the VM is created.
  config.vm.provision "deps", type: "shell", inline: <<-SHELL

    mkdir /tmp/downloads

    # Install dependencies.
    apt-get update
    apt-get install -y \
      apt-transport-https \
      ca-certificates \
      curl \
      gnupg-agent \
      jq \
      software-properties-common \
      zip

    nomad_version=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/nomad | jq -r '.current_version')
    consul_version=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/consul | jq -r '.current_version')

    # Download and install Docker.
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) \
      stable"
    apt-get update
    apt-get install -y \
      docker-ce \
      docker-ce-cli \
      containerd.io
    docker run hello-world
    usermod -aG docker vagrant

    # Download and install Hey.
    pushd /tmp/downloads
    curl --silent --show-error --remote-name-all \
      https://storage.googleapis.com/hey-release/hey_linux_amd64
    mv hey_linux_amd64 /usr/local/bin/hey
    chmod +x /usr/local/bin/hey
    popd

    # Download and install Nomad and Consul.
    pushd /tmp/downloads
    curl --silent --show-error --remote-name-all \
      https://releases.hashicorp.com/nomad/${nomad_version}/nomad_${nomad_version}_linux_amd64.zip \
      https://releases.hashicorp.com/consul/${consul_version}/consul_${consul_version}_linux_amd64.zip
    unzip nomad_${nomad_version}_linux_amd64.zip
    unzip consul_${consul_version}_linux_amd64.zip
    mkdir -p /opt/hashicorp/bin
    mv nomad consul /opt/hashicorp/bin
    chmod +x /opt/hashicorp/bin/{nomad,consul}
    ln -s /opt/hashicorp/bin/{nomad,consul} /usr/local/bin
    popd

    rm -fr /tmp/downloads
  SHELL

  # Setup demo dependencies.
  #   - Create daemons for Nomad and Consul
  # Runs everytime the VM starts.
  config.vm.provision "app:setup", type: "shell", run: "always", inline: <<-SHELL
    # create paths for Nomad host volumes
    mkdir -p /opt/nomad-volumes
    pushd /opt/nomad-volumes
    mkdir -p grafana
    chown 472:472 grafana
    popd

    # configure Nomad and Consul daemons
    pushd /home/vagrant/nomad-autoscaler/files
    for t in consul nomad; do
      cp ${t}.service /etc/systemd/system/
      mkdir -p /etc/${t}.d
      cp ${t}.hcl /etc/${t}.d/
      systemctl enable $t
      systemctl start $t
    done
    popd
  SHELL

end
