# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Expose ports to the host.
  config.vm.network "forwarded_port", guest: 4646, host: 4646, host_ip: "127.0.0.1" # Nomad HTTP API/UI
  config.vm.network "forwarded_port", guest: 8500, host: 8500, host_ip: "127.0.0.1" # Consul HTTP API/UI
  config.vm.network "forwarded_port", guest: 9090, host: 9090, host_ip: "127.0.0.1" # Prometheus HTTP API/UI

  # Share current directory with jobs and configuration files with the VM. Add
  # the shared files in a sub-dir.
  config.vm.synced_folder "./", "/home/vagrant/nomad-autoscaler"
  config.vm.synced_folder "../shared", "/home/vagrant/nomad-autoscaler-shared"

  # VM configuration.
  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--uartmode1", "file", File::NULL ]
    vb.memory = "4096"
    vb.cpus = 2
  end

  # Provision demo dependencies.
  #   - Downloads and install Nomad, Consul and Docker
  # Only runs when the VM is created.
  config.vm.provision "deps", type: "shell", inline: <<-SHELL

    mkdir /tmp/downloads

    # Install dependencies.
    apt-get update
    apt-get install -y \
      apt-transport-https \
      ca-certificates \
      curl \
      gnupg-agent \
      jq \
      redis-server \
      software-properties-common \
      zip

    nomad_version=1.0.0-beta2+ent
    consul_version=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/consul | jq -r '.current_version')

    # Download and install Docker.
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) \
      stable"
    apt-get update
    apt-get install -y \
      docker-ce \
      docker-ce-cli \
      containerd.io
    docker run hello-world
    usermod -aG docker vagrant

    // Create the HashiCorp binary destination.
    mkdir -p /opt/hashicorp/bin

    # Download the Autoscaler Binary.
    pushd /tmp/downloads
    curl --silent --show-error --remote-name-all \
      https://releases.hashicorp.com/nomad-autoscaler/0.2.0-beta2+ent/nomad-autoscaler_0.2.0-beta2+ent_linux_amd64.zip
    unzip nomad-autoscaler_0.2.0-beta1+ent_linux_amd64.zip
    mv nomad-autoscaler /opt/hashicorp/bin
    chmod +x /opt/hashicorp/bin/nomad-autoscaler
    cp /opt/hashicorp/bin/nomad-autoscaler /bin
    popd

    # Download and install Nomad and Consul.
    pushd /tmp/downloads
    curl --silent --show-error --remote-name-all \
      https://releases.hashicorp.com/nomad/${nomad_version}/nomad_${nomad_version}_linux_amd64.zip \
      https://releases.hashicorp.com/consul/${consul_version}/consul_${consul_version}_linux_amd64.zip
    unzip nomad_${nomad_version}_linux_amd64.zip
    unzip consul_${consul_version}_linux_amd64.zip
    mv nomad consul /opt/hashicorp/bin
    chmod +x /opt/hashicorp/bin/{nomad,consul}
    ln -s /opt/hashicorp/bin/{nomad,consul} /usr/local/bin
    popd

    rm -fr /tmp/downloads
  SHELL

  # Setup demo dependencies.
  #   - Create daemons for Nomad and Consul
  # Runs everytime the VM starts.
  config.vm.provision "app:setup", type: "shell", run: "always", inline: <<-SHELL
    # Configure the Nomad and Consul daemons.
    pushd /home/vagrant/nomad-autoscaler-shared
    for t in consul nomad; do
      cp ${t}.service /etc/systemd/system/
      mkdir -p /etc/${t}.d
    done
    popd

    # Copy across the config files.
    cp /home/vagrant/nomad-autoscaler-shared/consul.hcl /etc/consul.d/
    cp /home/vagrant/nomad-autoscaler/files/nomad.hcl /etc/nomad.d/

    # Enable and start the daemons
    systemctl enable consul
    systemctl start consul
    sudo systemctl enable nomad
    sudo systemctl start nomad
  SHELL

end
