// Copyright IBM Corp. 2020, 2025
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugins/strategy/proto/v1/strategy.proto

package proto

import (
	v1 "github.com/hashicorp/nomad-autoscaler/plugins/shared/proto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunRequest struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Action            *v1.ScalingAction       `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Check             *v1.ScalingPolicyCheck  `protobuf:"bytes,2,opt,name=check,proto3" json:"check,omitempty"`
	TimestampedMetric []*v1.TimestampedMetric `protobuf:"bytes,3,rep,name=timestamped_metric,json=timestampedMetric,proto3" json:"timestamped_metric,omitempty"`
	Count             int64                   `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_plugins_strategy_proto_v1_strategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_strategy_proto_v1_strategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_plugins_strategy_proto_v1_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetAction() *v1.ScalingAction {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *RunRequest) GetCheck() *v1.ScalingPolicyCheck {
	if x != nil {
		return x.Check
	}
	return nil
}

func (x *RunRequest) GetTimestampedMetric() []*v1.TimestampedMetric {
	if x != nil {
		return x.TimestampedMetric
	}
	return nil
}

func (x *RunRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RunResponse struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Action            *v1.ScalingAction       `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Check             *v1.ScalingPolicyCheck  `protobuf:"bytes,2,opt,name=check,proto3" json:"check,omitempty"`
	TimestampedMetric []*v1.TimestampedMetric `protobuf:"bytes,3,rep,name=timestamped_metric,json=timestampedMetric,proto3" json:"timestamped_metric,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_plugins_strategy_proto_v1_strategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_strategy_proto_v1_strategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_plugins_strategy_proto_v1_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *RunResponse) GetAction() *v1.ScalingAction {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *RunResponse) GetCheck() *v1.ScalingPolicyCheck {
	if x != nil {
		return x.Check
	}
	return nil
}

func (x *RunResponse) GetTimestampedMetric() []*v1.TimestampedMetric {
	if x != nil {
		return x.TimestampedMetric
	}
	return nil
}

var File_plugins_strategy_proto_v1_strategy_proto protoreflect.FileDescriptor

const file_plugins_strategy_proto_v1_strategy_proto_rawDesc = "" +
	"\n" +
	"(plugins/strategy/proto/v1/strategy.proto\x124hashicorp.nomad_autoscaler.plugins.strategy.proto.v1\x1a$plugins/shared/proto/v1/shared.proto\"\xd1\x02\n" +
	"\n" +
	"RunRequest\x12Y\n" +
	"\x06action\x18\x01 \x01(\v2A.hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingActionR\x06action\x12\\\n" +
	"\x05check\x18\x02 \x01(\v2F.hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyCheckR\x05check\x12t\n" +
	"\x12timestamped_metric\x18\x03 \x03(\v2E.hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimestampedMetricR\x11timestampedMetric\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\"\xbc\x02\n" +
	"\vRunResponse\x12Y\n" +
	"\x06action\x18\x01 \x01(\v2A.hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingActionR\x06action\x12\\\n" +
	"\x05check\x18\x02 \x01(\v2F.hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyCheckR\x05check\x12t\n" +
	"\x12timestamped_metric\x18\x03 \x03(\v2E.hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimestampedMetricR\x11timestampedMetric2\xa6\x01\n" +
	"\x15StrategyPluginService\x12\x8c\x01\n" +
	"\x03Run\x12@.hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.RunRequest\x1aA.hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.RunResponse\"\x00B\aZ\x05protob\x06proto3"

var (
	file_plugins_strategy_proto_v1_strategy_proto_rawDescOnce sync.Once
	file_plugins_strategy_proto_v1_strategy_proto_rawDescData []byte
)

func file_plugins_strategy_proto_v1_strategy_proto_rawDescGZIP() []byte {
	file_plugins_strategy_proto_v1_strategy_proto_rawDescOnce.Do(func() {
		file_plugins_strategy_proto_v1_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugins_strategy_proto_v1_strategy_proto_rawDesc), len(file_plugins_strategy_proto_v1_strategy_proto_rawDesc)))
	})
	return file_plugins_strategy_proto_v1_strategy_proto_rawDescData
}

var file_plugins_strategy_proto_v1_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugins_strategy_proto_v1_strategy_proto_goTypes = []any{
	(*RunRequest)(nil),            // 0: hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.RunRequest
	(*RunResponse)(nil),           // 1: hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.RunResponse
	(*v1.ScalingAction)(nil),      // 2: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingAction
	(*v1.ScalingPolicyCheck)(nil), // 3: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyCheck
	(*v1.TimestampedMetric)(nil),  // 4: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimestampedMetric
}
var file_plugins_strategy_proto_v1_strategy_proto_depIdxs = []int32{
	2, // 0: hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.RunRequest.action:type_name -> hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingAction
	3, // 1: hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.RunRequest.check:type_name -> hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyCheck
	4, // 2: hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.RunRequest.timestamped_metric:type_name -> hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimestampedMetric
	2, // 3: hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.RunResponse.action:type_name -> hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingAction
	3, // 4: hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.RunResponse.check:type_name -> hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyCheck
	4, // 5: hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.RunResponse.timestamped_metric:type_name -> hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimestampedMetric
	0, // 6: hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.StrategyPluginService.Run:input_type -> hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.RunRequest
	1, // 7: hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.StrategyPluginService.Run:output_type -> hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.RunResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_plugins_strategy_proto_v1_strategy_proto_init() }
func file_plugins_strategy_proto_v1_strategy_proto_init() {
	if File_plugins_strategy_proto_v1_strategy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugins_strategy_proto_v1_strategy_proto_rawDesc), len(file_plugins_strategy_proto_v1_strategy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugins_strategy_proto_v1_strategy_proto_goTypes,
		DependencyIndexes: file_plugins_strategy_proto_v1_strategy_proto_depIdxs,
		MessageInfos:      file_plugins_strategy_proto_v1_strategy_proto_msgTypes,
	}.Build()
	File_plugins_strategy_proto_v1_strategy_proto = out.File
	file_plugins_strategy_proto_v1_strategy_proto_goTypes = nil
	file_plugins_strategy_proto_v1_strategy_proto_depIdxs = nil
}
