// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugins/strategy/proto/v1/strategy.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1 "github.com/hashicorp/nomad-autoscaler/plugins/shared/proto/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RunRequest struct {
	Action               *v1.ScalingAction       `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Check                *v1.ScalingPolicyCheck  `protobuf:"bytes,2,opt,name=check,proto3" json:"check,omitempty"`
	TimestampedMetric    []*v1.TimestampedMetric `protobuf:"bytes,3,rep,name=timestamped_metric,json=timestampedMetric,proto3" json:"timestamped_metric,omitempty"`
	Count                int64                   `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RunRequest) Reset()         { *m = RunRequest{} }
func (m *RunRequest) String() string { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()    {}
func (*RunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07009cc895ac7ae9, []int{0}
}

func (m *RunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest.Unmarshal(m, b)
}
func (m *RunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest.Marshal(b, m, deterministic)
}
func (m *RunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest.Merge(m, src)
}
func (m *RunRequest) XXX_Size() int {
	return xxx_messageInfo_RunRequest.Size(m)
}
func (m *RunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest proto.InternalMessageInfo

func (m *RunRequest) GetAction() *v1.ScalingAction {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *RunRequest) GetCheck() *v1.ScalingPolicyCheck {
	if m != nil {
		return m.Check
	}
	return nil
}

func (m *RunRequest) GetTimestampedMetric() []*v1.TimestampedMetric {
	if m != nil {
		return m.TimestampedMetric
	}
	return nil
}

func (m *RunRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type RunResponse struct {
	Action               *v1.ScalingAction       `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Check                *v1.ScalingPolicyCheck  `protobuf:"bytes,2,opt,name=check,proto3" json:"check,omitempty"`
	TimestampedMetric    []*v1.TimestampedMetric `protobuf:"bytes,3,rep,name=timestamped_metric,json=timestampedMetric,proto3" json:"timestamped_metric,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RunResponse) Reset()         { *m = RunResponse{} }
func (m *RunResponse) String() string { return proto.CompactTextString(m) }
func (*RunResponse) ProtoMessage()    {}
func (*RunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07009cc895ac7ae9, []int{1}
}

func (m *RunResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunResponse.Unmarshal(m, b)
}
func (m *RunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunResponse.Marshal(b, m, deterministic)
}
func (m *RunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunResponse.Merge(m, src)
}
func (m *RunResponse) XXX_Size() int {
	return xxx_messageInfo_RunResponse.Size(m)
}
func (m *RunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunResponse proto.InternalMessageInfo

func (m *RunResponse) GetAction() *v1.ScalingAction {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *RunResponse) GetCheck() *v1.ScalingPolicyCheck {
	if m != nil {
		return m.Check
	}
	return nil
}

func (m *RunResponse) GetTimestampedMetric() []*v1.TimestampedMetric {
	if m != nil {
		return m.TimestampedMetric
	}
	return nil
}

func init() {
	proto.RegisterType((*RunRequest)(nil), "hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.RunRequest")
	proto.RegisterType((*RunResponse)(nil), "hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.RunResponse")
}

func init() {
	proto.RegisterFile("plugins/strategy/proto/v1/strategy.proto", fileDescriptor_07009cc895ac7ae9)
}

var fileDescriptor_07009cc895ac7ae9 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0xd3, 0xc1, 0x4a, 0x33, 0x31,
	0x10, 0x00, 0xe0, 0x7f, 0xbb, 0x7f, 0x2b, 0xa4, 0x27, 0x83, 0xc2, 0xd2, 0x53, 0x29, 0x1e, 0xf6,
	0x94, 0xd2, 0xea, 0x03, 0x58, 0x45, 0x6f, 0x42, 0x49, 0xbd, 0x28, 0x42, 0x89, 0xe9, 0xd0, 0x0d,
	0xee, 0x26, 0x6b, 0x32, 0x59, 0xe8, 0x3b, 0xf8, 0x1c, 0x3e, 0x85, 0x2f, 0xe1, 0x1b, 0x89, 0xd9,
	0xa5, 0xad, 0x9e, 0xb4, 0xbd, 0x7a, 0x0a, 0x33, 0x49, 0xbe, 0x81, 0xc9, 0x84, 0xa4, 0x65, 0xee,
	0x97, 0x4a, 0xbb, 0xa1, 0x43, 0x2b, 0x10, 0x96, 0xab, 0x61, 0x69, 0x0d, 0x9a, 0x61, 0x35, 0x5a,
	0x67, 0x58, 0xc8, 0xd0, 0xb3, 0x4c, 0xb8, 0x4c, 0x49, 0x63, 0x4b, 0xa6, 0x4d, 0x21, 0x16, 0x73,
	0xe1, 0xd1, 0x38, 0x29, 0x72, 0xb0, 0xac, 0x41, 0xd8, 0xd7, 0x2b, 0xac, 0x1a, 0xf5, 0x4e, 0xd6,
	0x7e, 0x26, 0x2c, 0x2c, 0xb6, 0xf4, 0x10, 0xd7, 0x07, 0x07, 0xef, 0x2d, 0x42, 0xb8, 0xd7, 0x1c,
	0x9e, 0x3d, 0x38, 0xa4, 0x77, 0xa4, 0x23, 0x24, 0x2a, 0xa3, 0x93, 0xa8, 0x1f, 0xa5, 0xdd, 0xf1,
	0x84, 0xfd, 0xa4, 0xf6, 0x16, 0xc8, 0xaa, 0x11, 0x9b, 0x49, 0x91, 0x2b, 0xbd, 0x9c, 0x04, 0x88,
	0x37, 0x20, 0x7d, 0x20, 0x6d, 0x99, 0x81, 0x7c, 0x4a, 0x5a, 0x41, 0xbe, 0xde, 0x43, 0x9e, 0x9a,
	0x5c, 0xc9, 0xd5, 0xe5, 0xa7, 0xc6, 0x6b, 0x94, 0x22, 0xa1, 0xa8, 0x0a, 0x70, 0x28, 0x8a, 0x12,
	0x16, 0xf3, 0x02, 0xd0, 0x2a, 0x99, 0xc4, 0xfd, 0x38, 0xed, 0x8e, 0xaf, 0x76, 0x29, 0x75, 0xbb,
	0xd1, 0x6e, 0x02, 0xc6, 0x0f, 0xf1, 0x7b, 0x8a, 0x1e, 0x91, 0xb6, 0x34, 0x5e, 0x63, 0xf2, 0xbf,
	0x1f, 0xa5, 0x31, 0xaf, 0x83, 0xc1, 0x5b, 0x8b, 0x74, 0x43, 0x4f, 0x5d, 0x69, 0xb4, 0x83, 0xbf,
	0xa6, 0xfe, 0xaa, 0xa9, 0xe3, 0xd7, 0x88, 0x1c, 0xcf, 0x9a, 0x71, 0x9e, 0x06, 0x68, 0x06, 0xb6,
	0x52, 0x12, 0xe8, 0x4b, 0x44, 0x62, 0xee, 0x35, 0x3d, 0x67, 0xbb, 0xfc, 0x08, 0xb6, 0x99, 0xf3,
	0xde, 0x64, 0x0f, 0xa1, 0x7e, 0xd5, 0xc1, 0xbf, 0x8b, 0x83, 0xfb, 0x76, 0xd8, 0x79, 0xec, 0x84,
	0xe5, 0xf4, 0x23, 0x00, 0x00, 0xff, 0xff, 0x47, 0xa3, 0xee, 0x78, 0xd3, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StrategyPluginServiceClient is the client API for StrategyPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StrategyPluginServiceClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
}

type strategyPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStrategyPluginServiceClient(cc grpc.ClientConnInterface) StrategyPluginServiceClient {
	return &strategyPluginServiceClient{cc}
}

func (c *strategyPluginServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.StrategyPluginService/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategyPluginServiceServer is the server API for StrategyPluginService service.
type StrategyPluginServiceServer interface {
	Run(context.Context, *RunRequest) (*RunResponse, error)
}

// UnimplementedStrategyPluginServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStrategyPluginServiceServer struct {
}

func (*UnimplementedStrategyPluginServiceServer) Run(ctx context.Context, req *RunRequest) (*RunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}

func RegisterStrategyPluginServiceServer(s *grpc.Server, srv StrategyPluginServiceServer) {
	s.RegisterService(&_StrategyPluginService_serviceDesc, srv)
}

func _StrategyPluginService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyPluginServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.StrategyPluginService/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyPluginServiceServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StrategyPluginService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.StrategyPluginService",
	HandlerType: (*StrategyPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _StrategyPluginService_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugins/strategy/proto/v1/strategy.proto",
}
