// Copyright IBM Corp. 2020, 2025
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: plugins/strategy/proto/v1/strategy.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StrategyPluginService_Run_FullMethodName = "/hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.StrategyPluginService/Run"
)

// StrategyPluginServiceClient is the client API for StrategyPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StrategyPluginServiceClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
}

type strategyPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStrategyPluginServiceClient(cc grpc.ClientConnInterface) StrategyPluginServiceClient {
	return &strategyPluginServiceClient{cc}
}

func (c *strategyPluginServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, StrategyPluginService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategyPluginServiceServer is the server API for StrategyPluginService service.
// All implementations should embed UnimplementedStrategyPluginServiceServer
// for forward compatibility.
type StrategyPluginServiceServer interface {
	Run(context.Context, *RunRequest) (*RunResponse, error)
}

// UnimplementedStrategyPluginServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStrategyPluginServiceServer struct{}

func (UnimplementedStrategyPluginServiceServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedStrategyPluginServiceServer) testEmbeddedByValue() {}

// UnsafeStrategyPluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StrategyPluginServiceServer will
// result in compilation errors.
type UnsafeStrategyPluginServiceServer interface {
	mustEmbedUnimplementedStrategyPluginServiceServer()
}

func RegisterStrategyPluginServiceServer(s grpc.ServiceRegistrar, srv StrategyPluginServiceServer) {
	// If the following call pancis, it indicates UnimplementedStrategyPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StrategyPluginService_ServiceDesc, srv)
}

func _StrategyPluginService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyPluginServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyPluginService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyPluginServiceServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StrategyPluginService_ServiceDesc is the grpc.ServiceDesc for StrategyPluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StrategyPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hashicorp.nomad_autoscaler.plugins.strategy.proto.v1.StrategyPluginService",
	HandlerType: (*StrategyPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _StrategyPluginService_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugins/strategy/proto/v1/strategy.proto",
}
