// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugins/shared/proto/v1/shared.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScalingDirection int32

const (
	ScalingDirection_SCALING_DIRECTION_UNSPECIFIED ScalingDirection = 0
	ScalingDirection_SCALING_DIRECTION_NONE        ScalingDirection = 1
	ScalingDirection_SCALING_DIRECTION_DOWN        ScalingDirection = 2
	ScalingDirection_SCALING_DIRECTION_UP          ScalingDirection = 3
)

var ScalingDirection_name = map[int32]string{
	0: "SCALING_DIRECTION_UNSPECIFIED",
	1: "SCALING_DIRECTION_NONE",
	2: "SCALING_DIRECTION_DOWN",
	3: "SCALING_DIRECTION_UP",
}

var ScalingDirection_value = map[string]int32{
	"SCALING_DIRECTION_UNSPECIFIED": 0,
	"SCALING_DIRECTION_NONE":        1,
	"SCALING_DIRECTION_DOWN":        2,
	"SCALING_DIRECTION_UP":          3,
}

func (x ScalingDirection) String() string {
	return proto.EnumName(ScalingDirection_name, int32(x))
}

func (ScalingDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65bd8f1fc7c159b7, []int{0}
}

type ScalingAction struct {
	Count                int64            `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Reason               string           `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Error                bool             `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	Direction            ScalingDirection `protobuf:"varint,4,opt,name=direction,proto3,enum=hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingDirection" json:"direction,omitempty"`
	Meta                 *any.Any         `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ScalingAction) Reset()         { *m = ScalingAction{} }
func (m *ScalingAction) String() string { return proto.CompactTextString(m) }
func (*ScalingAction) ProtoMessage()    {}
func (*ScalingAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_65bd8f1fc7c159b7, []int{0}
}

func (m *ScalingAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalingAction.Unmarshal(m, b)
}
func (m *ScalingAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalingAction.Marshal(b, m, deterministic)
}
func (m *ScalingAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalingAction.Merge(m, src)
}
func (m *ScalingAction) XXX_Size() int {
	return xxx_messageInfo_ScalingAction.Size(m)
}
func (m *ScalingAction) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalingAction.DiscardUnknown(m)
}

var xxx_messageInfo_ScalingAction proto.InternalMessageInfo

func (m *ScalingAction) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ScalingAction) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *ScalingAction) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *ScalingAction) GetDirection() ScalingDirection {
	if m != nil {
		return m.Direction
	}
	return ScalingDirection_SCALING_DIRECTION_UNSPECIFIED
}

func (m *ScalingAction) GetMeta() *any.Any {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ScalingPolicyCheck struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source               string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Query                string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	QueryWindow          *duration.Duration     `protobuf:"bytes,4,opt,name=query_window,json=queryWindow,proto3" json:"query_window,omitempty"`
	Strategy             *ScalingPolicyStrategy `protobuf:"bytes,5,opt,name=strategy,proto3" json:"strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ScalingPolicyCheck) Reset()         { *m = ScalingPolicyCheck{} }
func (m *ScalingPolicyCheck) String() string { return proto.CompactTextString(m) }
func (*ScalingPolicyCheck) ProtoMessage()    {}
func (*ScalingPolicyCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_65bd8f1fc7c159b7, []int{1}
}

func (m *ScalingPolicyCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalingPolicyCheck.Unmarshal(m, b)
}
func (m *ScalingPolicyCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalingPolicyCheck.Marshal(b, m, deterministic)
}
func (m *ScalingPolicyCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalingPolicyCheck.Merge(m, src)
}
func (m *ScalingPolicyCheck) XXX_Size() int {
	return xxx_messageInfo_ScalingPolicyCheck.Size(m)
}
func (m *ScalingPolicyCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalingPolicyCheck.DiscardUnknown(m)
}

var xxx_messageInfo_ScalingPolicyCheck proto.InternalMessageInfo

func (m *ScalingPolicyCheck) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScalingPolicyCheck) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ScalingPolicyCheck) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *ScalingPolicyCheck) GetQueryWindow() *duration.Duration {
	if m != nil {
		return m.QueryWindow
	}
	return nil
}

func (m *ScalingPolicyCheck) GetStrategy() *ScalingPolicyStrategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

type ScalingPolicyStrategy struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config               map[string]string `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ScalingPolicyStrategy) Reset()         { *m = ScalingPolicyStrategy{} }
func (m *ScalingPolicyStrategy) String() string { return proto.CompactTextString(m) }
func (*ScalingPolicyStrategy) ProtoMessage()    {}
func (*ScalingPolicyStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_65bd8f1fc7c159b7, []int{2}
}

func (m *ScalingPolicyStrategy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalingPolicyStrategy.Unmarshal(m, b)
}
func (m *ScalingPolicyStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalingPolicyStrategy.Marshal(b, m, deterministic)
}
func (m *ScalingPolicyStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalingPolicyStrategy.Merge(m, src)
}
func (m *ScalingPolicyStrategy) XXX_Size() int {
	return xxx_messageInfo_ScalingPolicyStrategy.Size(m)
}
func (m *ScalingPolicyStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalingPolicyStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_ScalingPolicyStrategy proto.InternalMessageInfo

func (m *ScalingPolicyStrategy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScalingPolicyStrategy) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

type TimeRange struct {
	To                   *timestamp.Timestamp `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TimeRange) Reset()         { *m = TimeRange{} }
func (m *TimeRange) String() string { return proto.CompactTextString(m) }
func (*TimeRange) ProtoMessage()    {}
func (*TimeRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_65bd8f1fc7c159b7, []int{3}
}

func (m *TimeRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRange.Unmarshal(m, b)
}
func (m *TimeRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRange.Marshal(b, m, deterministic)
}
func (m *TimeRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRange.Merge(m, src)
}
func (m *TimeRange) XXX_Size() int {
	return xxx_messageInfo_TimeRange.Size(m)
}
func (m *TimeRange) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRange.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRange proto.InternalMessageInfo

func (m *TimeRange) GetTo() *timestamp.Timestamp {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TimeRange) GetFrom() *timestamp.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

type TimestampedMetric struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value                float64              `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TimestampedMetric) Reset()         { *m = TimestampedMetric{} }
func (m *TimestampedMetric) String() string { return proto.CompactTextString(m) }
func (*TimestampedMetric) ProtoMessage()    {}
func (*TimestampedMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_65bd8f1fc7c159b7, []int{4}
}

func (m *TimestampedMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimestampedMetric.Unmarshal(m, b)
}
func (m *TimestampedMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimestampedMetric.Marshal(b, m, deterministic)
}
func (m *TimestampedMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimestampedMetric.Merge(m, src)
}
func (m *TimestampedMetric) XXX_Size() int {
	return xxx_messageInfo_TimestampedMetric.Size(m)
}
func (m *TimestampedMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_TimestampedMetric.DiscardUnknown(m)
}

var xxx_messageInfo_TimestampedMetric proto.InternalMessageInfo

func (m *TimestampedMetric) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *TimestampedMetric) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterEnum("hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingDirection", ScalingDirection_name, ScalingDirection_value)
	proto.RegisterType((*ScalingAction)(nil), "hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingAction")
	proto.RegisterType((*ScalingPolicyCheck)(nil), "hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyCheck")
	proto.RegisterType((*ScalingPolicyStrategy)(nil), "hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyStrategy")
	proto.RegisterMapType((map[string]string)(nil), "hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyStrategy.ConfigEntry")
	proto.RegisterType((*TimeRange)(nil), "hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimeRange")
	proto.RegisterType((*TimestampedMetric)(nil), "hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimestampedMetric")
}

func init() {
	proto.RegisterFile("plugins/shared/proto/v1/shared.proto", fileDescriptor_65bd8f1fc7c159b7)
}

var fileDescriptor_65bd8f1fc7c159b7 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0x71, 0xdb, 0x8d, 0xd5, 0x01, 0x14, 0xac, 0x31, 0x65, 0x95, 0x80, 0x50, 0x71, 0x88,
	0x76, 0x70, 0xb5, 0x70, 0x19, 0x88, 0xcb, 0x68, 0x0a, 0x8a, 0x04, 0xd9, 0xe4, 0x6e, 0x9a, 0xc4,
	0xa5, 0xf2, 0x12, 0x2f, 0x8d, 0x96, 0xd8, 0xc5, 0x71, 0x36, 0xe5, 0x09, 0x78, 0x42, 0x1e, 0x80,
	0xe7, 0xe0, 0x82, 0xe2, 0xb8, 0xdb, 0xd8, 0x2a, 0x04, 0x82, 0x53, 0xfd, 0xcf, 0xf7, 0xf7, 0xdf,
	0xdf, 0xef, 0xb3, 0x0b, 0x5f, 0x2e, 0xf2, 0x2a, 0xcd, 0x78, 0x39, 0x2a, 0xe7, 0x54, 0xb2, 0x64,
	0xb4, 0x90, 0x42, 0x89, 0xd1, 0xc5, 0xae, 0xd1, 0x58, 0x6b, 0xe4, 0xcf, 0x69, 0x39, 0xcf, 0x62,
	0x21, 0x17, 0x98, 0x8b, 0x82, 0x26, 0x33, 0x5a, 0x29, 0x51, 0xc6, 0x34, 0x67, 0x12, 0x9b, 0x00,
	0x7c, 0x73, 0x03, 0xbe, 0xd8, 0x1d, 0x6c, 0xa7, 0x42, 0xa4, 0x39, 0x6b, 0x13, 0x4f, 0xab, 0xb3,
	0x11, 0xe5, 0x75, 0x5b, 0x1d, 0x3c, 0xbb, 0x5d, 0x4a, 0x2a, 0x49, 0x55, 0x26, 0xb8, 0xa9, 0x3f,
	0xbf, 0x5d, 0x57, 0x59, 0xc1, 0x4a, 0x45, 0x8b, 0x45, 0x6b, 0x18, 0x7e, 0x07, 0xf0, 0xe1, 0x34,
	0xa6, 0x79, 0xc6, 0xd3, 0xfd, 0xb8, 0xd9, 0x88, 0x36, 0xe1, 0x5a, 0x2c, 0x2a, 0xae, 0x1c, 0xe0,
	0x02, 0xaf, 0x4b, 0x5a, 0x81, 0xb6, 0xe0, 0xba, 0x64, 0xb4, 0x14, 0xdc, 0xe9, 0xb8, 0xc0, 0xeb,
	0x13, 0xa3, 0x1a, 0x37, 0x93, 0x52, 0x48, 0xa7, 0xeb, 0x02, 0x6f, 0x83, 0xb4, 0x02, 0x9d, 0xc2,
	0x7e, 0x92, 0x49, 0xa6, 0x03, 0x9d, 0x9e, 0x0b, 0xbc, 0x47, 0x7e, 0x80, 0xff, 0x9e, 0x1c, 0x9b,
	0xce, 0x82, 0x65, 0x16, 0xb9, 0x8e, 0x45, 0x1e, 0xec, 0x15, 0x4c, 0x51, 0x67, 0xcd, 0x05, 0x9e,
	0xe5, 0x6f, 0xe2, 0x96, 0x14, 0x2f, 0x49, 0xf1, 0x3e, 0xaf, 0x89, 0x76, 0x0c, 0x7f, 0x00, 0x88,
	0x4c, 0xd2, 0xa1, 0xc8, 0xb3, 0xb8, 0x1e, 0xcf, 0x59, 0x7c, 0x8e, 0x10, 0xec, 0x71, 0x5a, 0x30,
	0xcd, 0xd9, 0x27, 0x7a, 0xdd, 0x60, 0x96, 0xa2, 0x92, 0x31, 0x5b, 0x62, 0xb6, 0xaa, 0xc1, 0xfc,
	0x52, 0x31, 0x59, 0x6b, 0xcc, 0x3e, 0x69, 0x05, 0x7a, 0x0b, 0x1f, 0xe8, 0xc5, 0xec, 0x32, 0xe3,
	0x89, 0xb8, 0xd4, 0xa4, 0x96, 0xbf, 0x7d, 0xa7, 0x95, 0xc0, 0x5c, 0x0a, 0xb1, 0xb4, 0xfd, 0x44,
	0xbb, 0x11, 0x83, 0x1b, 0xa5, 0x92, 0x54, 0xb1, 0xb4, 0x36, 0x10, 0xe1, 0x3f, 0xcc, 0xa8, 0x25,
	0x9b, 0x9a, 0x40, 0x72, 0x15, 0x3d, 0xfc, 0x06, 0xe0, 0x93, 0x95, 0x9e, 0x95, 0x03, 0x28, 0xe0,
	0x7a, 0x2c, 0xf8, 0x59, 0x96, 0x3a, 0x1d, 0xb7, 0xeb, 0x59, 0xfe, 0xf1, 0x7f, 0x6b, 0x09, 0x8f,
	0x75, 0xee, 0x84, 0x2b, 0x59, 0x13, 0x73, 0xc8, 0xe0, 0x35, 0xb4, 0x6e, 0x7c, 0x46, 0x36, 0xec,
	0x9e, 0xb3, 0xda, 0x34, 0xd4, 0x2c, 0x9b, 0xc1, 0x5f, 0xd0, 0xbc, 0x5a, 0xde, 0x47, 0x2b, 0xde,
	0x74, 0xf6, 0xc0, 0x30, 0x85, 0xfd, 0xa3, 0xac, 0x60, 0x84, 0xf2, 0x94, 0xa1, 0x1d, 0xd8, 0x51,
	0x42, 0xef, 0xb3, 0xfc, 0xc1, 0x9d, 0xf9, 0x1f, 0x2d, 0x1f, 0x3d, 0xe9, 0x28, 0x81, 0x30, 0xec,
	0x9d, 0x49, 0x51, 0xe8, 0xc4, 0xdf, 0xbb, 0xb5, 0x6f, 0x18, 0xc3, 0xc7, 0x57, 0x9f, 0x58, 0xf2,
	0x89, 0x29, 0x99, 0xc5, 0x68, 0x0f, 0xf6, 0xaf, 0xfe, 0x4a, 0x7f, 0x70, 0xee, 0xb5, 0xf9, 0x57,
	0x22, 0x60, 0x88, 0x76, 0xbe, 0x02, 0x68, 0xdf, 0x7e, 0xed, 0xe8, 0x05, 0x7c, 0x3a, 0x1d, 0xef,
	0x7f, 0x0c, 0xa3, 0x0f, 0xb3, 0x20, 0x24, 0x93, 0xf1, 0x51, 0x78, 0x10, 0xcd, 0x8e, 0xa3, 0xe9,
	0xe1, 0x64, 0x1c, 0xbe, 0x0f, 0x27, 0x81, 0x7d, 0x0f, 0x0d, 0xe0, 0xd6, 0x5d, 0x4b, 0x74, 0x10,
	0x4d, 0x6c, 0xb0, 0xba, 0x16, 0x1c, 0x9c, 0x44, 0x76, 0x07, 0x39, 0x70, 0x73, 0x45, 0xf4, 0xa1,
	0xdd, 0x7d, 0x77, 0xff, 0xf3, 0x5a, 0x0b, 0xb0, 0xae, 0x7f, 0x5e, 0xfd, 0x0c, 0x00, 0x00, 0xff,
	0xff, 0xa7, 0xea, 0x15, 0x08, 0xd9, 0x04, 0x00, 0x00,
}
