// Copyright IBM Corp. 2020, 2025
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugins/shared/proto/v1/shared.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScalingDirection int32

const (
	ScalingDirection_SCALING_DIRECTION_UNSPECIFIED ScalingDirection = 0
	ScalingDirection_SCALING_DIRECTION_NONE        ScalingDirection = 1
	ScalingDirection_SCALING_DIRECTION_DOWN        ScalingDirection = 2
	ScalingDirection_SCALING_DIRECTION_UP          ScalingDirection = 3
)

// Enum value maps for ScalingDirection.
var (
	ScalingDirection_name = map[int32]string{
		0: "SCALING_DIRECTION_UNSPECIFIED",
		1: "SCALING_DIRECTION_NONE",
		2: "SCALING_DIRECTION_DOWN",
		3: "SCALING_DIRECTION_UP",
	}
	ScalingDirection_value = map[string]int32{
		"SCALING_DIRECTION_UNSPECIFIED": 0,
		"SCALING_DIRECTION_NONE":        1,
		"SCALING_DIRECTION_DOWN":        2,
		"SCALING_DIRECTION_UP":          3,
	}
)

func (x ScalingDirection) Enum() *ScalingDirection {
	p := new(ScalingDirection)
	*p = x
	return p
}

func (x ScalingDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScalingDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_plugins_shared_proto_v1_shared_proto_enumTypes[0].Descriptor()
}

func (ScalingDirection) Type() protoreflect.EnumType {
	return &file_plugins_shared_proto_v1_shared_proto_enumTypes[0]
}

func (x ScalingDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScalingDirection.Descriptor instead.
func (ScalingDirection) EnumDescriptor() ([]byte, []int) {
	return file_plugins_shared_proto_v1_shared_proto_rawDescGZIP(), []int{0}
}

type ScalingAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Error         bool                   `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	Direction     ScalingDirection       `protobuf:"varint,4,opt,name=direction,proto3,enum=hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingDirection" json:"direction,omitempty"`
	Meta          *anypb.Any             `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalingAction) Reset() {
	*x = ScalingAction{}
	mi := &file_plugins_shared_proto_v1_shared_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalingAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalingAction) ProtoMessage() {}

func (x *ScalingAction) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_shared_proto_v1_shared_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalingAction.ProtoReflect.Descriptor instead.
func (*ScalingAction) Descriptor() ([]byte, []int) {
	return file_plugins_shared_proto_v1_shared_proto_rawDescGZIP(), []int{0}
}

func (x *ScalingAction) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ScalingAction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ScalingAction) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ScalingAction) GetDirection() ScalingDirection {
	if x != nil {
		return x.Direction
	}
	return ScalingDirection_SCALING_DIRECTION_UNSPECIFIED
}

func (x *ScalingAction) GetMeta() *anypb.Any {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ScalingPolicyCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	QueryWindow   *durationpb.Duration   `protobuf:"bytes,4,opt,name=query_window,json=queryWindow,proto3" json:"query_window,omitempty"`
	Strategy      *ScalingPolicyStrategy `protobuf:"bytes,5,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalingPolicyCheck) Reset() {
	*x = ScalingPolicyCheck{}
	mi := &file_plugins_shared_proto_v1_shared_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalingPolicyCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalingPolicyCheck) ProtoMessage() {}

func (x *ScalingPolicyCheck) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_shared_proto_v1_shared_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalingPolicyCheck.ProtoReflect.Descriptor instead.
func (*ScalingPolicyCheck) Descriptor() ([]byte, []int) {
	return file_plugins_shared_proto_v1_shared_proto_rawDescGZIP(), []int{1}
}

func (x *ScalingPolicyCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScalingPolicyCheck) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ScalingPolicyCheck) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ScalingPolicyCheck) GetQueryWindow() *durationpb.Duration {
	if x != nil {
		return x.QueryWindow
	}
	return nil
}

func (x *ScalingPolicyCheck) GetStrategy() *ScalingPolicyStrategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

type ScalingPolicyStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalingPolicyStrategy) Reset() {
	*x = ScalingPolicyStrategy{}
	mi := &file_plugins_shared_proto_v1_shared_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalingPolicyStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalingPolicyStrategy) ProtoMessage() {}

func (x *ScalingPolicyStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_shared_proto_v1_shared_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalingPolicyStrategy.ProtoReflect.Descriptor instead.
func (*ScalingPolicyStrategy) Descriptor() ([]byte, []int) {
	return file_plugins_shared_proto_v1_shared_proto_rawDescGZIP(), []int{2}
}

func (x *ScalingPolicyStrategy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScalingPolicyStrategy) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_plugins_shared_proto_v1_shared_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_shared_proto_v1_shared_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_plugins_shared_proto_v1_shared_proto_rawDescGZIP(), []int{3}
}

func (x *TimeRange) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *TimeRange) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

type TimestampedMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampedMetric) Reset() {
	*x = TimestampedMetric{}
	mi := &file_plugins_shared_proto_v1_shared_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampedMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampedMetric) ProtoMessage() {}

func (x *TimestampedMetric) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_shared_proto_v1_shared_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampedMetric.ProtoReflect.Descriptor instead.
func (*TimestampedMetric) Descriptor() ([]byte, []int) {
	return file_plugins_shared_proto_v1_shared_proto_rawDescGZIP(), []int{4}
}

func (x *TimestampedMetric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TimestampedMetric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_plugins_shared_proto_v1_shared_proto protoreflect.FileDescriptor

const file_plugins_shared_proto_v1_shared_proto_rawDesc = "" +
	"\n" +
	"$plugins/shared/proto/v1/shared.proto\x122hashicorp.nomad_autoscaler.plugins.shared.proto.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe1\x01\n" +
	"\rScalingAction\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x14\n" +
	"\x05error\x18\x03 \x01(\bR\x05error\x12b\n" +
	"\tdirection\x18\x04 \x01(\x0e2D.hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingDirectionR\tdirection\x12(\n" +
	"\x04meta\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\x04meta\"\xfb\x01\n" +
	"\x12ScalingPolicyCheck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12<\n" +
	"\fquery_window\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\vqueryWindow\x12e\n" +
	"\bstrategy\x18\x05 \x01(\v2I.hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyStrategyR\bstrategy\"\xd5\x01\n" +
	"\x15ScalingPolicyStrategy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12m\n" +
	"\x06config\x18\x02 \x03(\v2U.hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyStrategy.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\tTimeRange\x12*\n" +
	"\x02to\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\"c\n" +
	"\x11TimestampedMetric\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value*\x87\x01\n" +
	"\x10ScalingDirection\x12!\n" +
	"\x1dSCALING_DIRECTION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SCALING_DIRECTION_NONE\x10\x01\x12\x1a\n" +
	"\x16SCALING_DIRECTION_DOWN\x10\x02\x12\x18\n" +
	"\x14SCALING_DIRECTION_UP\x10\x03B\aZ\x05protob\x06proto3"

var (
	file_plugins_shared_proto_v1_shared_proto_rawDescOnce sync.Once
	file_plugins_shared_proto_v1_shared_proto_rawDescData []byte
)

func file_plugins_shared_proto_v1_shared_proto_rawDescGZIP() []byte {
	file_plugins_shared_proto_v1_shared_proto_rawDescOnce.Do(func() {
		file_plugins_shared_proto_v1_shared_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugins_shared_proto_v1_shared_proto_rawDesc), len(file_plugins_shared_proto_v1_shared_proto_rawDesc)))
	})
	return file_plugins_shared_proto_v1_shared_proto_rawDescData
}

var file_plugins_shared_proto_v1_shared_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugins_shared_proto_v1_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_plugins_shared_proto_v1_shared_proto_goTypes = []any{
	(ScalingDirection)(0),         // 0: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingDirection
	(*ScalingAction)(nil),         // 1: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingAction
	(*ScalingPolicyCheck)(nil),    // 2: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyCheck
	(*ScalingPolicyStrategy)(nil), // 3: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyStrategy
	(*TimeRange)(nil),             // 4: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimeRange
	(*TimestampedMetric)(nil),     // 5: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimestampedMetric
	nil,                           // 6: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyStrategy.ConfigEntry
	(*anypb.Any)(nil),             // 7: google.protobuf.Any
	(*durationpb.Duration)(nil),   // 8: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_plugins_shared_proto_v1_shared_proto_depIdxs = []int32{
	0, // 0: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingAction.direction:type_name -> hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingDirection
	7, // 1: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingAction.meta:type_name -> google.protobuf.Any
	8, // 2: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyCheck.query_window:type_name -> google.protobuf.Duration
	3, // 3: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyCheck.strategy:type_name -> hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyStrategy
	6, // 4: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyStrategy.config:type_name -> hashicorp.nomad_autoscaler.plugins.shared.proto.v1.ScalingPolicyStrategy.ConfigEntry
	9, // 5: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimeRange.to:type_name -> google.protobuf.Timestamp
	9, // 6: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimeRange.from:type_name -> google.protobuf.Timestamp
	9, // 7: hashicorp.nomad_autoscaler.plugins.shared.proto.v1.TimestampedMetric.timestamp:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_plugins_shared_proto_v1_shared_proto_init() }
func file_plugins_shared_proto_v1_shared_proto_init() {
	if File_plugins_shared_proto_v1_shared_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugins_shared_proto_v1_shared_proto_rawDesc), len(file_plugins_shared_proto_v1_shared_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugins_shared_proto_v1_shared_proto_goTypes,
		DependencyIndexes: file_plugins_shared_proto_v1_shared_proto_depIdxs,
		EnumInfos:         file_plugins_shared_proto_v1_shared_proto_enumTypes,
		MessageInfos:      file_plugins_shared_proto_v1_shared_proto_msgTypes,
	}.Build()
	File_plugins_shared_proto_v1_shared_proto = out.File
	file_plugins_shared_proto_v1_shared_proto_goTypes = nil
	file_plugins_shared_proto_v1_shared_proto_depIdxs = nil
}
