# This GitHub action triggers a fresh set of Nomad Autoscaler builds
# and publishes them to GitHub Releases under the `nightly` tag.
# Note that artifacts available via GitHub Releases are not codesigned or
# notarized.
# Failures are reported to slack.
name: Nightly Release

on:
  schedule:
    # Runs against the default branch every day overnight
    - cron: "18 3 * * *"
  workflow_dispatch:

jobs:
  # Build a fresh set of artifacts
  build-artifacts:
    uses: ./.github/workflows/build.yml
  github-release:
    needs: build-artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Download built artifacts
        uses: actions/download-artifact@v2
        with:
          path: out/
      # Set BUILD_OUTPUT_LIST to out\<project>-<version>.<fileext>\*,out\...
      # This is needed to attach the build artifacts to the GitHub Release
      - name: Set BUILD_OUTPUT_LIST
        run: |
          echo "$(ls -xm1 out/)" > tmp.txt
          cat tmp.txt | sed 's:.*:out/&/*:' > tmp2.txt
          echo "BUILD_OUTPUT_LIST=$(cat tmp2.txt | tr '\n' ',' | perl -ple 'chop')" >> $GITHUB_ENV
          rm -rf tmp.txt && rm -rf tmp2.txt
      - name: Advance nightly tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
                await github.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: "tags/nightly"
                })
            } catch (e) {
              console.log("Warning: The nightly tag doesn't exist yet, so there's nothing to do. Trace: " + e)
            }
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/nightly",
              sha: context.sha
            })
      # This will create a new GitHub Release called `nightly`
      # If a release with this name already exists, it will overwrite the existing data
      - name: Create a nightly GitHub prerelease
        id: create_prerelease
        uses: ncipollo/release-action@v1
        with:
          name: nightly
          artifacts: "${{ env.BUILD_OUTPUT_LIST }}"
          tag: nightly
          bodyFile: ".github/workflows/nightly-release-readme.md"
          prerelease: true
          allowUpdates: true
          removeArtifacts: true
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish nightly GitHub prerelease
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_prerelease.outputs.id }}
  # Send a slack notification if either job defined above fails
  slack-notify:
    needs:
      - build-artifacts
      - github-release
    if: always() && (needs.build-artifacts.result == 'failure' || needs.github-release.result == 'failure')
    runs-on: ubuntu-20.04
    steps:
      - name: Send slack notification on failure
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": ":x::moon::nomad-sob: Nomad Autoscaler Nightly Release *FAILED*",
              "attachments": [
                {
                  "color": "#C41E3A",
                  "blocks": [
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Branch:*\n`${{ github.ref_name }}`"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Ref:*\n${{ github.sha }}"
                        }
                      ]
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Workflow:*\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          # the slack webhook url links to #feed-nomad-releases
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
