// Copyright IBM Corp. 2020, 2025
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugins/base/proto/v1/base.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginType int32

const (
	PluginType_PLUGIN_TYPE_UNSPECIFIED PluginType = 0
	PluginType_PLUGIN_TYPE_APM         PluginType = 1
	PluginType_PLUGIN_TYPE_STRATEGY    PluginType = 2
	PluginType_PLUGIN_TYPE_TARGET      PluginType = 3
)

// Enum value maps for PluginType.
var (
	PluginType_name = map[int32]string{
		0: "PLUGIN_TYPE_UNSPECIFIED",
		1: "PLUGIN_TYPE_APM",
		2: "PLUGIN_TYPE_STRATEGY",
		3: "PLUGIN_TYPE_TARGET",
	}
	PluginType_value = map[string]int32{
		"PLUGIN_TYPE_UNSPECIFIED": 0,
		"PLUGIN_TYPE_APM":         1,
		"PLUGIN_TYPE_STRATEGY":    2,
		"PLUGIN_TYPE_TARGET":      3,
	}
)

func (x PluginType) Enum() *PluginType {
	p := new(PluginType)
	*p = x
	return p
}

func (x PluginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugins_base_proto_v1_base_proto_enumTypes[0].Descriptor()
}

func (PluginType) Type() protoreflect.EnumType {
	return &file_plugins_base_proto_v1_base_proto_enumTypes[0]
}

func (x PluginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginType.Descriptor instead.
func (PluginType) EnumDescriptor() ([]byte, []int) {
	return file_plugins_base_proto_v1_base_proto_rawDescGZIP(), []int{0}
}

type PluginInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfoRequest) Reset() {
	*x = PluginInfoRequest{}
	mi := &file_plugins_base_proto_v1_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfoRequest) ProtoMessage() {}

func (x *PluginInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_base_proto_v1_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfoRequest.ProtoReflect.Descriptor instead.
func (*PluginInfoRequest) Descriptor() ([]byte, []int) {
	return file_plugins_base_proto_v1_base_proto_rawDescGZIP(), []int{0}
}

type PluginInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          PluginType             `protobuf:"varint,2,opt,name=type,proto3,enum=hashicorp.nomad_autoscaler.plugins.base.proto.v1.PluginType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfoResponse) Reset() {
	*x = PluginInfoResponse{}
	mi := &file_plugins_base_proto_v1_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfoResponse) ProtoMessage() {}

func (x *PluginInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_base_proto_v1_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfoResponse.ProtoReflect.Descriptor instead.
func (*PluginInfoResponse) Descriptor() ([]byte, []int) {
	return file_plugins_base_proto_v1_base_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfoResponse) GetType() PluginType {
	if x != nil {
		return x.Type
	}
	return PluginType_PLUGIN_TYPE_UNSPECIFIED
}

type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_plugins_base_proto_v1_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_base_proto_v1_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_plugins_base_proto_v1_base_proto_rawDescGZIP(), []int{2}
}

func (x *SetConfigRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type SetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	mi := &file_plugins_base_proto_v1_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_base_proto_v1_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigResponse.ProtoReflect.Descriptor instead.
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return file_plugins_base_proto_v1_base_proto_rawDescGZIP(), []int{3}
}

var File_plugins_base_proto_v1_base_proto protoreflect.FileDescriptor

const file_plugins_base_proto_v1_base_proto_rawDesc = "" +
	"\n" +
	" plugins/base/proto/v1/base.proto\x120hashicorp.nomad_autoscaler.plugins.base.proto.v1\"\x13\n" +
	"\x11PluginInfoRequest\"z\n" +
	"\x12PluginInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12P\n" +
	"\x04type\x18\x02 \x01(\x0e2<.hashicorp.nomad_autoscaler.plugins.base.proto.v1.PluginTypeR\x04type\"\xb5\x01\n" +
	"\x10SetConfigRequest\x12f\n" +
	"\x06config\x18\x01 \x03(\v2N.hashicorp.nomad_autoscaler.plugins.base.proto.v1.SetConfigRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x13\n" +
	"\x11SetConfigResponse*p\n" +
	"\n" +
	"PluginType\x12\x1b\n" +
	"\x17PLUGIN_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPLUGIN_TYPE_APM\x10\x01\x12\x18\n" +
	"\x14PLUGIN_TYPE_STRATEGY\x10\x02\x12\x16\n" +
	"\x12PLUGIN_TYPE_TARGET\x10\x032\xc8\x02\n" +
	"\x11BasePluginService\x12\x99\x01\n" +
	"\n" +
	"PluginInfo\x12C.hashicorp.nomad_autoscaler.plugins.base.proto.v1.PluginInfoRequest\x1aD.hashicorp.nomad_autoscaler.plugins.base.proto.v1.PluginInfoResponse\"\x00\x12\x96\x01\n" +
	"\tSetConfig\x12B.hashicorp.nomad_autoscaler.plugins.base.proto.v1.SetConfigRequest\x1aC.hashicorp.nomad_autoscaler.plugins.base.proto.v1.SetConfigResponse\"\x00B\aZ\x05protob\x06proto3"

var (
	file_plugins_base_proto_v1_base_proto_rawDescOnce sync.Once
	file_plugins_base_proto_v1_base_proto_rawDescData []byte
)

func file_plugins_base_proto_v1_base_proto_rawDescGZIP() []byte {
	file_plugins_base_proto_v1_base_proto_rawDescOnce.Do(func() {
		file_plugins_base_proto_v1_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugins_base_proto_v1_base_proto_rawDesc), len(file_plugins_base_proto_v1_base_proto_rawDesc)))
	})
	return file_plugins_base_proto_v1_base_proto_rawDescData
}

var file_plugins_base_proto_v1_base_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugins_base_proto_v1_base_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_plugins_base_proto_v1_base_proto_goTypes = []any{
	(PluginType)(0),            // 0: hashicorp.nomad_autoscaler.plugins.base.proto.v1.PluginType
	(*PluginInfoRequest)(nil),  // 1: hashicorp.nomad_autoscaler.plugins.base.proto.v1.PluginInfoRequest
	(*PluginInfoResponse)(nil), // 2: hashicorp.nomad_autoscaler.plugins.base.proto.v1.PluginInfoResponse
	(*SetConfigRequest)(nil),   // 3: hashicorp.nomad_autoscaler.plugins.base.proto.v1.SetConfigRequest
	(*SetConfigResponse)(nil),  // 4: hashicorp.nomad_autoscaler.plugins.base.proto.v1.SetConfigResponse
	nil,                        // 5: hashicorp.nomad_autoscaler.plugins.base.proto.v1.SetConfigRequest.ConfigEntry
}
var file_plugins_base_proto_v1_base_proto_depIdxs = []int32{
	0, // 0: hashicorp.nomad_autoscaler.plugins.base.proto.v1.PluginInfoResponse.type:type_name -> hashicorp.nomad_autoscaler.plugins.base.proto.v1.PluginType
	5, // 1: hashicorp.nomad_autoscaler.plugins.base.proto.v1.SetConfigRequest.config:type_name -> hashicorp.nomad_autoscaler.plugins.base.proto.v1.SetConfigRequest.ConfigEntry
	1, // 2: hashicorp.nomad_autoscaler.plugins.base.proto.v1.BasePluginService.PluginInfo:input_type -> hashicorp.nomad_autoscaler.plugins.base.proto.v1.PluginInfoRequest
	3, // 3: hashicorp.nomad_autoscaler.plugins.base.proto.v1.BasePluginService.SetConfig:input_type -> hashicorp.nomad_autoscaler.plugins.base.proto.v1.SetConfigRequest
	2, // 4: hashicorp.nomad_autoscaler.plugins.base.proto.v1.BasePluginService.PluginInfo:output_type -> hashicorp.nomad_autoscaler.plugins.base.proto.v1.PluginInfoResponse
	4, // 5: hashicorp.nomad_autoscaler.plugins.base.proto.v1.BasePluginService.SetConfig:output_type -> hashicorp.nomad_autoscaler.plugins.base.proto.v1.SetConfigResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_plugins_base_proto_v1_base_proto_init() }
func file_plugins_base_proto_v1_base_proto_init() {
	if File_plugins_base_proto_v1_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugins_base_proto_v1_base_proto_rawDesc), len(file_plugins_base_proto_v1_base_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugins_base_proto_v1_base_proto_goTypes,
		DependencyIndexes: file_plugins_base_proto_v1_base_proto_depIdxs,
		EnumInfos:         file_plugins_base_proto_v1_base_proto_enumTypes,
		MessageInfos:      file_plugins_base_proto_v1_base_proto_msgTypes,
	}.Build()
	File_plugins_base_proto_v1_base_proto = out.File
	file_plugins_base_proto_v1_base_proto_goTypes = nil
	file_plugins_base_proto_v1_base_proto_depIdxs = nil
}
