// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugins/base/proto/v1/base.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PluginType int32

const (
	PluginType_PLUGIN_TYPE_UNSPECIFIED PluginType = 0
	PluginType_PLUGIN_TYPE_APM         PluginType = 1
	PluginType_PLUGIN_TYPE_STRATEGY    PluginType = 2
	PluginType_PLUGIN_TYPE_TARGET      PluginType = 3
)

var PluginType_name = map[int32]string{
	0: "PLUGIN_TYPE_UNSPECIFIED",
	1: "PLUGIN_TYPE_APM",
	2: "PLUGIN_TYPE_STRATEGY",
	3: "PLUGIN_TYPE_TARGET",
}

var PluginType_value = map[string]int32{
	"PLUGIN_TYPE_UNSPECIFIED": 0,
	"PLUGIN_TYPE_APM":         1,
	"PLUGIN_TYPE_STRATEGY":    2,
	"PLUGIN_TYPE_TARGET":      3,
}

func (x PluginType) String() string {
	return proto.EnumName(PluginType_name, int32(x))
}

func (PluginType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6fc979e0130464c1, []int{0}
}

type PluginInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginInfoRequest) Reset()         { *m = PluginInfoRequest{} }
func (m *PluginInfoRequest) String() string { return proto.CompactTextString(m) }
func (*PluginInfoRequest) ProtoMessage()    {}
func (*PluginInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fc979e0130464c1, []int{0}
}

func (m *PluginInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginInfoRequest.Unmarshal(m, b)
}
func (m *PluginInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginInfoRequest.Marshal(b, m, deterministic)
}
func (m *PluginInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginInfoRequest.Merge(m, src)
}
func (m *PluginInfoRequest) XXX_Size() int {
	return xxx_messageInfo_PluginInfoRequest.Size(m)
}
func (m *PluginInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PluginInfoRequest proto.InternalMessageInfo

type PluginInfoResponse struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 PluginType `protobuf:"varint,2,opt,name=type,proto3,enum=hashicorp.nomad_autoscaler.plugins.base.proto.v1.PluginType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PluginInfoResponse) Reset()         { *m = PluginInfoResponse{} }
func (m *PluginInfoResponse) String() string { return proto.CompactTextString(m) }
func (*PluginInfoResponse) ProtoMessage()    {}
func (*PluginInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fc979e0130464c1, []int{1}
}

func (m *PluginInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginInfoResponse.Unmarshal(m, b)
}
func (m *PluginInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginInfoResponse.Marshal(b, m, deterministic)
}
func (m *PluginInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginInfoResponse.Merge(m, src)
}
func (m *PluginInfoResponse) XXX_Size() int {
	return xxx_messageInfo_PluginInfoResponse.Size(m)
}
func (m *PluginInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PluginInfoResponse proto.InternalMessageInfo

func (m *PluginInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PluginInfoResponse) GetType() PluginType {
	if m != nil {
		return m.Type
	}
	return PluginType_PLUGIN_TYPE_UNSPECIFIED
}

type SetConfigRequest struct {
	Config               map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fc979e0130464c1, []int{2}
}

func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(m, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigResponse) Reset()         { *m = SetConfigResponse{} }
func (m *SetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigResponse) ProtoMessage()    {}
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fc979e0130464c1, []int{3}
}

func (m *SetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigResponse.Unmarshal(m, b)
}
func (m *SetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigResponse.Merge(m, src)
}
func (m *SetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigResponse.Size(m)
}
func (m *SetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("hashicorp.nomad_autoscaler.plugins.base.proto.v1.PluginType", PluginType_name, PluginType_value)
	proto.RegisterType((*PluginInfoRequest)(nil), "hashicorp.nomad_autoscaler.plugins.base.proto.v1.PluginInfoRequest")
	proto.RegisterType((*PluginInfoResponse)(nil), "hashicorp.nomad_autoscaler.plugins.base.proto.v1.PluginInfoResponse")
	proto.RegisterType((*SetConfigRequest)(nil), "hashicorp.nomad_autoscaler.plugins.base.proto.v1.SetConfigRequest")
	proto.RegisterMapType((map[string]string)(nil), "hashicorp.nomad_autoscaler.plugins.base.proto.v1.SetConfigRequest.ConfigEntry")
	proto.RegisterType((*SetConfigResponse)(nil), "hashicorp.nomad_autoscaler.plugins.base.proto.v1.SetConfigResponse")
}

func init() {
	proto.RegisterFile("plugins/base/proto/v1/base.proto", fileDescriptor_6fc979e0130464c1)
}

var fileDescriptor_6fc979e0130464c1 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xc1, 0x8e, 0x93, 0x50,
	0x14, 0x9d, 0x47, 0x67, 0xc6, 0xf4, 0x4e, 0xa2, 0xcc, 0x9d, 0x89, 0x92, 0xba, 0x21, 0xac, 0x1a,
	0x17, 0xaf, 0x4e, 0xdd, 0xa8, 0x71, 0xd3, 0x32, 0xd8, 0x90, 0x68, 0x43, 0x80, 0x59, 0xd4, 0x4d,
	0xf3, 0x8a, 0xaf, 0x2d, 0xb1, 0xe5, 0x21, 0x0f, 0x48, 0xf0, 0x43, 0x4c, 0xfc, 0x10, 0xff, 0xc1,
	0xcf, 0x32, 0x7d, 0x50, 0x4b, 0xdc, 0x75, 0xba, 0xe2, 0xde, 0x73, 0xe0, 0x9c, 0x7b, 0xcf, 0x05,
	0xcc, 0x74, 0x53, 0xac, 0xe2, 0x44, 0x0e, 0x16, 0x4c, 0xf2, 0x41, 0x9a, 0x89, 0x5c, 0x0c, 0xca,
	0x3b, 0xd5, 0x51, 0xd5, 0xe1, 0xeb, 0x35, 0x93, 0xeb, 0x38, 0x12, 0x59, 0x4a, 0x13, 0xb1, 0x65,
	0x5f, 0xe7, 0xac, 0xc8, 0x85, 0x8c, 0xd8, 0x86, 0x67, 0xb4, 0xf9, 0x98, 0x1e, 0x5e, 0xa7, 0xe5,
	0x9d, 0x75, 0x03, 0xd7, 0x9e, 0x22, 0xdc, 0x64, 0x29, 0x7c, 0xfe, 0xbd, 0xe0, 0x32, 0xb7, 0x7e,
	0x00, 0xb6, 0x41, 0x99, 0x8a, 0x44, 0x72, 0x44, 0x38, 0x4f, 0xd8, 0x96, 0x1b, 0xc4, 0x24, 0xfd,
	0xae, 0xaf, 0x6a, 0xf4, 0xe0, 0x3c, 0xaf, 0x52, 0x6e, 0x68, 0x26, 0xe9, 0x3f, 0x1d, 0x7e, 0xa0,
	0xc7, 0xfa, 0xd3, 0xda, 0x27, 0xac, 0x52, 0xee, 0x2b, 0x25, 0xeb, 0x37, 0x01, 0x3d, 0xe0, 0xb9,
	0x2d, 0x92, 0x65, 0xbc, 0x6a, 0x06, 0xc2, 0x25, 0x5c, 0x46, 0x0a, 0x30, 0x88, 0xd9, 0xe9, 0x5f,
	0x0d, 0xa7, 0xc7, 0x1b, 0xfd, 0xaf, 0x49, 0xeb, 0xce, 0x49, 0xf2, 0xac, 0xf2, 0x1b, 0xf5, 0xde,
	0x3b, 0xb8, 0x6a, 0xc1, 0xa8, 0x43, 0xe7, 0x1b, 0xaf, 0x9a, 0x85, 0x77, 0x25, 0xde, 0xc2, 0x45,
	0xc9, 0x36, 0x45, 0xbd, 0x70, 0xd7, 0xaf, 0x9b, 0xf7, 0xda, 0x5b, 0xb2, 0x0b, 0xb2, 0x65, 0x51,
	0x47, 0xf6, 0x2a, 0x05, 0x38, 0x2c, 0x88, 0x2f, 0xe1, 0x85, 0xf7, 0xe9, 0x61, 0xe2, 0x4e, 0xe7,
	0xe1, 0xcc, 0x73, 0xe6, 0x0f, 0xd3, 0xc0, 0x73, 0x6c, 0xf7, 0xa3, 0xeb, 0xdc, 0xeb, 0x67, 0x78,
	0x03, 0xcf, 0xda, 0xe4, 0xc8, 0xfb, 0xac, 0x13, 0x34, 0xe0, 0xb6, 0x0d, 0x06, 0xa1, 0x3f, 0x0a,
	0x9d, 0xc9, 0x4c, 0xd7, 0xf0, 0x39, 0x60, 0x9b, 0x09, 0x47, 0xfe, 0xc4, 0x09, 0xf5, 0xce, 0xf0,
	0x8f, 0x06, 0xd7, 0x63, 0x26, 0x79, 0x6d, 0x1b, 0xf0, 0xac, 0x8c, 0x23, 0x8e, 0xbf, 0xc8, 0x7e,
	0x90, 0xdd, 0x45, 0xd1, 0x7e, 0xec, 0x9d, 0x5a, 0x3f, 0x49, 0xef, 0xfe, 0x34, 0x91, 0x3a, 0x21,
	0xeb, 0x0c, 0x7f, 0x12, 0xe8, 0xfe, 0x4b, 0x0e, 0xc7, 0xa7, 0x5f, 0xb6, 0x67, 0x9f, 0xa4, 0xb1,
	0x1f, 0x6c, 0xfc, 0xe4, 0xcb, 0x85, 0xe2, 0x17, 0x97, 0xea, 0xf1, 0xe6, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf3, 0xbc, 0xcf, 0xa4, 0x80, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BasePluginServiceClient is the client API for BasePluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BasePluginServiceClient interface {
	PluginInfo(ctx context.Context, in *PluginInfoRequest, opts ...grpc.CallOption) (*PluginInfoResponse, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
}

type basePluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBasePluginServiceClient(cc grpc.ClientConnInterface) BasePluginServiceClient {
	return &basePluginServiceClient{cc}
}

func (c *basePluginServiceClient) PluginInfo(ctx context.Context, in *PluginInfoRequest, opts ...grpc.CallOption) (*PluginInfoResponse, error) {
	out := new(PluginInfoResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad_autoscaler.plugins.base.proto.v1.BasePluginService/PluginInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *basePluginServiceClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	out := new(SetConfigResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad_autoscaler.plugins.base.proto.v1.BasePluginService/SetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BasePluginServiceServer is the server API for BasePluginService service.
type BasePluginServiceServer interface {
	PluginInfo(context.Context, *PluginInfoRequest) (*PluginInfoResponse, error)
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
}

// UnimplementedBasePluginServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBasePluginServiceServer struct {
}

func (*UnimplementedBasePluginServiceServer) PluginInfo(ctx context.Context, req *PluginInfoRequest) (*PluginInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginInfo not implemented")
}
func (*UnimplementedBasePluginServiceServer) SetConfig(ctx context.Context, req *SetConfigRequest) (*SetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConfig not implemented")
}

func RegisterBasePluginServiceServer(s *grpc.Server, srv BasePluginServiceServer) {
	s.RegisterService(&_BasePluginService_serviceDesc, srv)
}

func _BasePluginService_PluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasePluginServiceServer).PluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad_autoscaler.plugins.base.proto.v1.BasePluginService/PluginInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasePluginServiceServer).PluginInfo(ctx, req.(*PluginInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BasePluginService_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasePluginServiceServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad_autoscaler.plugins.base.proto.v1.BasePluginService/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasePluginServiceServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BasePluginService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hashicorp.nomad_autoscaler.plugins.base.proto.v1.BasePluginService",
	HandlerType: (*BasePluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PluginInfo",
			Handler:    _BasePluginService_PluginInfo_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _BasePluginService_SetConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugins/base/proto/v1/base.proto",
}
